version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./your_schema_file.sql:/docker-entrypoint-initdb.d/your_schema_file.sql
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

