version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      POSTGRES_HOST: localhost
      POSTGRES_PORT: "5432"
    volumes:
      - ./kitabe-dede-qorqud.sql:/docker-entrypoint-initdb.d/kitabe-dede-qorqud.sql
  app:
    build: .
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - db

