version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - mynetwork
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork
networks:
  mynetwork:
