version: '3'
services:
  db:
    image: postgres
    pull_policy: build
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    #volumes:
      #- ./sample.sql:/docker-entrypoint-initdb.d/sample.sql
  app:
    pull_policy: build
    build: .
    environment:
      DEBUG: "true"
      PGHOST: db
      PGPORT: "5432"
      PGUSER: myuser
      PGPASSWORD: mypassword
      PGDATABASE: mydb
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db

