version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      PGUSER: myuser
      PGPASSWORD: mypassword
      PGDATABASE: mydb
      PGHOST: localhost
      PGPORT: "5432"
    volumes:
      - ./kitabe-dede-qorqud.sql:/docker-entrypoint-initdb.d/kitabe-dede-qorqud.sql
    ports:
      - "5432"
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

