name: deploy-project

on:
  push
   
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: RockeyWereWolf/docker-compose-gitops-action@master
        name: Remote Deployment
        with:
          remote_docker_host: ubuntu@129.151.196.195
          args: -p project up -d
          ssh_public_key: ${{ secrets.DEDE_SSH_KEY }}
          ssh_private_key: ${{ secrets.DEDE_SSH_PRIVATE_KEY }}
          compose_file_path: docker-compose.yml
