name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: TapTap21/docker-remote-deployment-action@v1.0
      name: Docker-Compose Remote Deployment
      with:
        remote_docker_host: 129.151.220.209
        ssh_private_key: ${{ secrets.DEDE_SSH_PRIVATE_KEY }}
        stack_file_name: docker-compose.yml
        docker_login_user: ${{ secrets.DEDE_SSH_USER }}
