name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: 129.151.220.209
        ssh_private_key: ${{ secrets.DEDE_SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.DEDE_SSH_USER }}
        docker_compose_prefix: DEDE
