name: deploy-project

on:
  push:
    paths:
      - 'project/**'
      - '.github/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: aosus/docker-compose-gitops-action@v1
        name: Remote Deployment
        with:
          remote_docker_host: root@100.107.201.124
          args: -p project up -d
          ssh_public_key: ${{ secrets.DEDE_SSH_KEY }}
          ssh_private_key: ${{ secrets.DEDE_SSH_PRIVATE_KEY }}
          compose_file_path: docker-compose.yml
